### ISSUE TITLE
Typo ModItems and .json for Armor

### ISSUE THREAD

**Issue by Mrkuff** [shadowfacts/shadowfacts.github.io#1]
copeprArmorMaterial typo.  ex.:

copperHelmet = register(new ItemArmor(TutorialMod.copeprArmorMaterial
copperChestplate = register(new ItemArmor(TutorialMod.copeprArmorMaterial

Etc.  
And armor models .json miss a ","
ex.:
copperHelmet.json
{
	"parent": "item/generated"      < ------ miss a , here
	"textures": {
		"layer0": "tutorial:items/copperHelmet"
	}
}

**Comment by shadowfacts** [comment]
Thanks for pointing those out! They've been fixed and should be live soon.

**Comment by Mrkuff** [comment]
No, Thanks to YOU!  I really like the way you code and i wanted to help you out. ( Well, help us all! )
looking foward for your implementation of a machine ( like a furnace with 2 input ) with recipe ( like Iron + Coal Coke for steel :D ) ... and your power implementation of course.  I may be your typo QA bit*h! eheh
