### ISSUE TITLE
Found other typo

### ISSUE THREAD

**Issue by Mrkuff** [shadowfacts/shadowfacts.github.io#2]
Hello, i've finish all your tuto (Really awesome) and i decided to write down all the little mismatch i got.  I know people can figure it out, but here they are :

JSON Item Models
-Link for copper ingot texture "https://raw.githubusercontent.com/CyanideX/Unity/master/assets/thermalfoundation/textures/items/material/IngotCopper.png" = 404.  Change it for : https://github.com/shadowfacts/TutorialMod/tree/master/src/main/resources/assets/tutorial/textures/items/ingotCopper.png

Basic Block
- Basic Items link = https://shadowfacts.net/tutorials/forge-modding-19/basic-items/
instead of https://shadowfacts.net/tutorials/forge-modding-1102/basic-items/

Forge Blockstates
-Link to "JSON Item Models tutorial." is "http://localhost:4000/tutorials/forge-modding-19/json-item-models/" instead of https://shadowfacts.net/tutorials/forge-modding-1102/json-item-models/
-copper ore texture = https://raw.githubusercontent.com/CyanideX/Unity/master/assets/thermalfoundation/textures/blocks/ore/Ore_Copper.png
instead of "https://github.com/shadowfacts/TutorialMod/tree/master/src/main/resources/assets/tutorial/textures/blocks/oreCopper.png"

Crops.  here the link work but are from "raw.githubusercontent.com".  I dont know if it's ok or not..
-Corn Seed Texture = https://raw.githubusercontent.com/shadowfacts/TutorialMod/master/src/main/resources/assets/tutorial/textures/items/cornSeed.png
instead of "https://github.com/shadowfacts/TutorialMod/tree/master/src/main/resources/assets/tutorial/textures/items/cornSeed.png"
-Corn Texture : https://raw.githubusercontent.com/shadowfacts/TutorialMod/master/src/main/resources/assets/tutorial/textures/items/corn.png
instead of "https://github.com/shadowfacts/TutorialMod/tree/master/src/main/resources/assets/tutorial/textures/items/corn.png"

Advanced Creative Tabs. Same as Crops
- Custom Background : https://raw.githubusercontent.com/shadowfacts/TutorialMod/master/src/main/resources/assets/minecraft/textures/gui/container/creative_inventory/tab_tutorialmod.png instead of "https://github.com/shadowfacts/TutorialMod/tree/master/src/main/resources/assets/minecraft/textures/gui/container/creative_inventory/tab_tutorialmod.png"

Tools:
- All texture = https://raw.githubusercontent.com/shadowfacts/TutorialMod/master/src/main/resources/assets/tutorial/textures/items/*.png
-CopperAxe.json use is :
{
	"parent": "item/handheld",
	"textures": {
		"layer0": "tutorial:items/copperHoe"  <-- typo
	}
}

Armor:
- All texture = https://raw.githubusercontent.com/shadowfacts/TutorialMod/master/src/main/resources/assets/tutorial/textures/items/*.png
- Copper Legging localization : item.copperLeggings.name=Copper Chestplate
- Copper boot localization : item.copperBoots.name=Copper Chestplate

Annndddddd that's all

**Comment by shadowfacts** [comment]
The textures linking to raw.githubusercontent.com is intentional because it allows people to directly download the textures if they aren't familiar with the GitHub interface.
